# Generated by Django 4.2.7 on 2023-12-02 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cancelled', 'cancelled'), ('in_transit', 'in_transit'), ('refunded', 'refunded'), ('shipped', 'shipped'), ('pending', 'pending'), ('delivered', 'delivered')], default='pending', max_length=20),
        ),
    ]
