# Generated by Django 4.2.7 on 2023-12-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_date_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cancelled', 'cancelled'), ('in_transit', 'in_transit'), ('refunded', 'refunded'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('PLACED', 'placed')], default='PLACED', max_length=20),
        ),
    ]
